<a href="https://colab.research.google.com/github/ShreePurvaja/Data-Science-Notes/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 27.02.2025

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

# PANDAS

1.Deals only tabular data

2.1d - series like [1,2,3] (S)

3.2d - data frame like matrix (DA)

4.3d - panel ...cube shaped datas used in ct scances , svg ,vector formmat (PAN)

 so named **"PANDAS"**

# Series

In [ ]:
import pandas as pd

a = pd.Series([1, 2, 3, 4, 5])  # default index
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
import pandas as pd # useful for date and time manipulation

a = pd.Series([1, 2, 3, 4, 5],index = ['a', 'b', 'c', 'd', 'e'])  # index can be changed
print(a)

print([a['d']]) # index can be used to access elements

print(a['a':'c']) # slicing is possible

print(a[[0, 2, 4]]) # indexing is possible

a    1
b    2
c    3
d    4
e    5
dtype: int64
[4]
a    1
b    2
c    3
dtype: int64
a    1
c    3
e    5
dtype: int64

<ipython-input-15-db15ad72c0af>:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(a[[0, 2, 4]]) # indexing is possible

In [ ]:
a = pd.Series([1,2,3,4,5])  # arithmetic operations are possible
print(a+21)

print(a-2)

print(a*2)

print(a/2)

0    22
1    23
2    24
3    25
4    26
dtype: int64
0   -1
1    0
2    1
3    2
4    3
dtype: int64
0     2
1     4
2     6
3     8
4    10
dtype: int64
0    0.5
1    1.0
2    1.5
3    2.0
4    2.5
dtype: float64

In [ ]:
a=pd.Series([1,2,3,4,5])
b=pd.Series([10,20,30,40,50])

print(a+b)

0    11
1    22
2    33
3    44
4    55
dtype: int64

In [ ]:
a = pd.Series([1,2,3,4,5])

print(a>3)

print(a<3)

print(a==3)

print(a!=3)

0    False
1    False
2    False
3     True
4     True
dtype: bool
0     True
1     True
2    False
3    False
4    False
dtype: bool
0    False
1    False
2     True
3    False
4    False
dtype: bool
0     True
1     True
2    False
3     True
4     True
dtype: bool

In [ ]:
a = pd.Series([1,2,3,4,5])

print(a.apply(lambda x: x*2)) # lambda function is used to apply a function to all elements of a series

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
a = pd.Series([1,2,3,4,5])
print(a.apply(lambda x:'even' if x%2==0 else 'odd'))

0     odd
1    even
2     odd
3    even
4     odd
dtype: object

In [ ]:
#mathematical functions

print(a.sum())

print(a.mean()) # formula is mean = sum/n

print(a.max())

print(a.min())

print(a.median()) # formula is median = (n+1)/2

print(a.std())  # formula is standard deviation = sqrt(sum((x - mean)^2) / n)

print(a.var()) # formula is variance = sum((x - mean)^2) / n

15
3.0
5
1
3.0
1.5811388300841898
2.5

In [ ]:
a=pd.Series([1,2,2,4,5,6,1])
print(a.describe())
print("_______________________________","\n")


print(a.unique())
print("_______________________________","\n")


print(a.nunique()) # number of unique elements
print("________________________________","\n")


print(a.value_counts()) # frequency of each element
print("________________________________","\n")


print(a.is_unique)
print("________________________________","\n")


print(a.sort_values())
print("________________________________","\n")


print(a.sort_index())
print("________________________________","\n")


print(a.cumsum()) # meaning of cumulative sum is sum of first n elements

count    7.0
mean     3.0
std      2.0
min      1.0
25%      1.5
50%      2.0
75%      4.5
max      6.0
dtype: float64
_______________________________

[1 2 4 5 6]
_______________________________

5
________________________________

1    2
2    2
4    1
5    1
6    1
Name: count, dtype: int64
________________________________

False
________________________________

0    1
6    1
1    2
2    2
3    4
4    5
5    6
dtype: int64
________________________________

0    1
1    2
2    2
3    4
4    5
5    6
6    1
dtype: int64
________________________________

0     1
1     3
2     5
3     9
4    14
5    20
6    21
dtype: int64

# Dataframe - 2D

In [45]:
#to ectract data

import pandas as pd

d = pd.read_excel('/content/Student-Employability-Datasets.xlsx') # read data from excel file
display(d) # works only in notebook (not a method)

,Name of Student,GENERAL APPEARANCE,MANNER OF SPEAKING,PHYSICAL CONDITION,MENTAL ALERTNESS,SELF-CONFIDENCE,ABILITY TO PRESENT IDEAS,COMMUNICATION SKILLS,Student Performance Rating,CLASS
0,Student 1,4,5,4,5,5,5,5,5,Employable
1,Student 2,4,4,4,4,4,4,3,5,Employable
2,Student 3,4,3,3,3,3,3,2,5,LessEmployable
3,Student 4,3,3,3,2,3,3,3,5,LessEmployable
4,Student 5,4,4,3,3,4,4,3,5,Employable
...,...,...,...,...,...,...,...,...,...,...
2977,Student 2996,4,3,3,3,3,3,2,5,Employable
2978,Student 2997,3,4,4,4,4,4,4,5,Employable
2979,Student 2998,4,5,4,5,4,4,4,5,Employable
2980,Student 2999,4,4,4,3,4,4,3,5,LessEmployable
2981,Student 3000,4,4,4,4,3,4,4,5,Employable

In [46]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.1-py3-none-any.whl.metadata (4.4 kB)
Downloading PyMySQL-1.1.1-py3-none-any.whl (44 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.0/45.0 kB 3.6 MB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.1.1

In [54]:
# to extract data from database

import pymysql
import pandas as pd

# Database Configuration
DB_HOST = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"  # e.g., "localhost"
port = 4000
DB_USER = "2yYzWuNLpsRGRUo.root"       # e.g., "root"
DB_PASSWORD = "LziV3VzKcgY6K7lq"
DB_NAME = "guvi1"
TABLE_NAME = "Diabetes"

# Initialize connection to None
connection = None  # Initialize connection here

try:
    # Step 1: Connect to MySQL Database
    connection = pymysql.connect(
        host=DB_HOST,
        port=port,
        user=DB_USER,
        password=DB_PASSWORD,
        database=DB_NAME,
        ssl_verify_cert = True,
        ssl_verify_identity = True,
        cursorclass=pymysql.cursors.DictCursor  # This returns rows as dictionaries
    )

    print("✅ Successfully connected to the database.")

    # Step 2: Create a Cursor and Execute SQL Query
    with connection.cursor() as cursor:
        sql_query = f"SELECT * FROM {TABLE_NAME};"
        cursor.execute(sql_query)

        # Step 3: Fetch Data
        result = cursor.fetchall()

    # Step 4: Store Data in a Pandas DataFrame
    df = pd.DataFrame(result)

    # Display Data
    print("📊 Data retrieved from the database:")
    print(df.head())  # Show the first 5 rows

    # Step 5: (Optional) Save Data to CSV
    df.to_csv("database_output.csv", index=False)
    print("✅ Data saved to 'database_output.csv'.")

    # Step 6: (Optional) Save Data to JSON
    df.to_json("database_output.json", orient="records", indent=4)
    print("✅ Data saved to 'database_output.json'.")

except pymysql.MySQLError as e:
    print(f"❌ Error connecting to MySQL: {e}")

finally:
    # Step 7: Close Connection
    if connection:  # Now connection is defined even if the try block fails
        connection.close()
        print("🔌 MySQL connection closed.")

✅ Successfully connected to the database.
📊 Data retrieved from the database:
   pregnancies  glucose  bloodpressure  skinthickness  insulin   bmi  \
0            6      148             72             35        0  33.6
1            1       85             66             29        0  26.6
2            8      183             64              0        0  23.3
3            1       89             66             23       94  28.1
4            0      137             40             35      168  43.1

   diabetespedigreefunction  age  outcome
0                     0.627   50        1
1                     0.351   31        0
2                     0.672   32        1
3                     0.167   21        0
4                     2.288   33        1
✅ Data saved to 'database_output.csv'.
✅ Data saved to 'database_output.json'.
🔌 MySQL connection closed.

In [55]:
display(df)

,pregnancies,glucose,bloodpressure,skinthickness,insulin,bmi,diabetespedigreefunction,age,outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0