<a href="https://colab.research.google.com/github/ShreePurvaja/Data-Science-Notes/blob/main/Pandas_Functions%2Cdata%20cleaning(conti_).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 06.03.2025

In [3]:
import pandas as pd
airbnb = pd.read_csv('https://raw.githubusercontent.com/nethajinirmal13/Training-datasets/main/airbnb.csv?raw=true', index_col = 'Unnamed: 0')
display(airbnb)
airbnb.shape

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","(40.63222, -73.93398)",Private room,45$,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","(40.78761, -73.96862)",Entire home/apt,135$,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","(40.7007, -73.99517)",Entire home/apt,150$,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","(40.79169, -73.97498)",Entire home/apt,86$,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","(40.71884, -73.98354)",Private room,160$,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem","(40.80379, -73.95257)",Entire home/apt,105$,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem","(40.79531, -73.9333)",Entire home/apt,125$,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill","(40.68266, -73.96743000000002)",Entire home/apt,100$,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill","(40.68832, -73.96366)",Entire home/apt,450$,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side","(40.76174, -73.96625)",Private room,90$,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06

(10019, 16)

In [4]:
airbnb.info()#check the data type of each column

<class 'pandas.core.frame.DataFrame'>
Index: 10019 entries, 0 to 10018
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   listing_id          10019 non-null  int64
 1   name                10014 non-null  object
 2   host_id             10019 non-null  int64
 3   host_name           10017 non-null  object
 4   neighbourhood_full  10019 non-null  object
 5   coordinates         10019 non-null  object
 6   room_type           10019 non-null  object
 7   price               9781 non-null   object
 8   number_of_reviews   10019 non-null  int64
 9   last_review         7944 non-null   object
 10  reviews_per_month   7944 non-null   float64
 11  availability_365    10019 non-null  int64
 12  rating              7944 non-null   float64
 13  number_of_stays     7944 non-null   float64
 14  5_stars             7944 non-null   float64
 15  listing_added       10019 non-null  object
dtypes: float64(4), int64(4), object(8)
memory usage: 1.6+ MB

In [11]:
airbnb["price"]=airbnb["price"].str.replace("$","") #remove $
airbnb["price"]=airbnb["price"].astype(float) #convert string to float

AttributeError: Can only use .str accessor with string values!

In [12]:
display(airbnb) #now the $ symbol in price is removed

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","(40.63222, -73.93398)",Private room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","(40.78761, -73.96862)",Entire home/apt,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","(40.7007, -73.99517)",Entire home/apt,150.0,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","(40.79169, -73.97498)",Entire home/apt,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","(40.71884, -73.98354)",Private room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem","(40.80379, -73.95257)",Entire home/apt,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem","(40.79531, -73.9333)",Entire home/apt,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill","(40.68266, -73.96743000000002)",Entire home/apt,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill","(40.68832, -73.96366)",Entire home/apt,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side","(40.76174, -73.96625)",Private room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06

In [13]:
airbnb.isnull().sum() #check for null values

listing_id               0
name                     5
host_id                  0
host_name                2
neighbourhood_full       0
coordinates              0
room_type                0
price                  238
number_of_reviews        0
last_review           2075
reviews_per_month     2075
availability_365         0
rating                2075
number_of_stays       2075
5_stars               2075
listing_added            0
dtype: int64

In [14]:
airbnb["coordinates"]=airbnb["coordinates"].str.replace("(","")
airbnb["coordinates"]=airbnb["coordinates"].str.replace(")","")
display(airbnb) #removed () in coordinates

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","40.63222, -73.93398",Private room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","40.78761, -73.96862",Entire home/apt,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","40.7007, -73.99517",Entire home/apt,150.0,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","40.79169, -73.97498",Entire home/apt,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","40.71884, -73.98354",Private room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem","40.80379, -73.95257",Entire home/apt,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem","40.79531, -73.9333",Entire home/apt,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill","40.68266, -73.96743000000002",Entire home/apt,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill","40.68832, -73.96366",Entire home/apt,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side","40.76174, -73.96625",Private room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06

In [15]:
a=airbnb["coordinates"].str.split(",",expand=True) #splits into different columns
display(a)                                         #expand is used to create columns instead of displaying in list

              0                    1
0      40.63222            -73.93398
1      40.78761            -73.96862
2       40.7007            -73.99517
3      40.79169            -73.97498
4      40.71884            -73.98354
...         ...                  ...
10014  40.80379            -73.95257
10015  40.79531             -73.9333
10016  40.68266   -73.96743000000002
10017  40.68832            -73.96366
10018  40.76174            -73.96625

[10019 rows x 2 columns]

In [16]:
airbnb["lattitude"]=a[0]
airbnb["longitude"]=a[1]
display(airbnb)

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,lattitude,longitude
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","40.63222, -73.93398",Private room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08,40.63222,-73.93398
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","40.78761, -73.96862",Entire home/apt,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25,40.78761,-73.96862
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","40.7007, -73.99517",Entire home/apt,150.0,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15,40.7007,-73.99517
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","40.79169, -73.97498",Entire home/apt,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20,40.79169,-73.97498
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","40.71884, -73.98354",Private room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem","40.80379, -73.95257",Entire home/apt,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22,40.80379,-73.95257
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem","40.79531, -73.9333",Entire home/apt,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31,40.79531,-73.9333
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill","40.68266, -73.96743000000002",Entire home/apt,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24,40.68266,-73.96743000000002
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill","40.68832, -73.96366",Entire home/apt,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25,40.68832,-73.96366
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side","40.76174, -73.96625",Private room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06,40.76174,-73.96625

In [17]:
airbnb["lattitude"] = airbnb["lattitude"].astype(float) #type conversion
airbnb["longitude"] = airbnb["longitude"].astype(float)
display(airbnb)

,listing_id,name,host_id,host_name,neighbourhood_full,coordinates,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,lattitude,longitude
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands","40.63222, -73.93398",Private room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08,40.63222,-73.93398
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side","40.78761, -73.96862",Entire home/apt,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25,40.78761,-73.96862
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights","40.7007, -73.99517",Entire home/apt,150.0,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15,40.70070,-73.99517
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side","40.79169, -73.97498",Entire home/apt,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20,40.79169,-73.97498
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side","40.71884, -73.98354",Private room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem","40.80379, -73.95257",Entire home/apt,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22,40.80379,-73.95257
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem","40.79531, -73.9333",Entire home/apt,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31,40.79531,-73.93330
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill","40.68266, -73.96743000000002",Entire home/apt,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24,40.68266,-73.96743
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill","40.68832, -73.96366",Entire home/apt,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25,40.68832,-73.96366
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side","40.76174, -73.96625",Private room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06,40.76174,-73.96625

In [18]:
airbnb.drop(columns="coordinates", inplace=True)#deletes the coordinates colun
display(airbnb)

,listing_id,name,host_id,host_name,neighbourhood_full,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,lattitude,longitude
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands",Private room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08,40.63222,-73.93398
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side",Entire home/apt,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25,40.78761,-73.96862
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights",Entire home/apt,150.0,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15,40.70070,-73.99517
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side",Entire home/apt,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20,40.79169,-73.97498
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side",Private room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem",Entire home/apt,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22,40.80379,-73.95257
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem",Entire home/apt,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31,40.79531,-73.93330
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill",Entire home/apt,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24,40.68266,-73.96743
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill",Entire home/apt,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25,40.68832,-73.96366
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side",Private room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06,40.76174,-73.96625

In [20]:
airbnb["listing_id"].nunique() #unique values

9999

In [25]:
b=airbnb["listing_id"].duplicated(keep=False) #duplicate values
airbnb[b].sort_values("listing_id") #keep = False means shows all duplicated values

,listing_id,name,host_id,host_name,neighbourhood_full,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,lattitude,longitude
1145,253806,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,"Brooklyn, Greenpoint",Entire home/apt,199.0,43,2019-07-02,0.47,60,4.620238,51.6,0.861086,2018-12-27,40.73652,-73.95236
6562,253806,Loft Suite @ The Box House Hotel,417504,The Box House Hotel,"Brooklyn, Greenpoint",Entire home/apt,199.0,43,2019-07-02,0.47,60,4.620238,51.6,0.861086,2018-12-27,40.73652,-73.95236
8699,2044392,The heart of Williamsburg 2 bedroom,620218,Sarah,"Brooklyn, Williamsburg",Entire home/apt,245.0,0,NaN,NaN,0,NaN,NaN,NaN,2018-08-09,40.71257,-73.96149
5761,2044392,The heart of Williamsburg 2 bedroom,620218,Sarah,"Brooklyn, Williamsburg",Entire home/apt,250.0,0,NaN,NaN,0,NaN,NaN,NaN,2018-05-24,40.71257,-73.96149
4187,4244242,Best Bedroom in Bedstuy/Bushwick. Ensuite bath...,22023014,BrooklynSleeps,"Brooklyn, Bedford-Stuyvesant",Private room,73.0,110,2019-06-23,1.96,323,4.962314,132.0,0.809882,2018-12-18,40.69496,-73.93949
2871,4244242,Best Bedroom in Bedstuy/Bushwick. Ensuite bath...,22023014,BrooklynSleeps,"Brooklyn, Bedford-Stuyvesant",Private room,70.0,110,2019-06-23,1.96,323,4.962314,132.0,0.809882,2018-12-18,40.69496,-73.93949
77,7319856,450ft Square Studio in Gramercy NY,11773680,Adam,"Manhattan, Kips Bay",Entire home/apt,289.0,4,2016-05-22,0.09,225,3.903764,4.8,0.756381,2015-11-17,40.73813,-73.98098
2255,7319856,450ft Square Studio in Gramercy NY,11773680,Adam,"Manhattan, Kips Bay",Entire home/apt,280.0,4,2016-05-22,0.09,225,3.903764,4.8,0.756381,2015-11-17,40.73813,-73.98098
555,9078222,"Prospect Park 3 bdrm, Sleeps 8 (#2)",47219962,Babajide,"Brooklyn, Prospect-Lefferts Gardens",Entire home/apt,154.0,123,2019-07-01,2.74,263,3.466881,147.6,0.738191,2018-12-26,40.66086,-73.96159
7933,9078222,"Prospect Park 3 bdrm, Sleeps 8 (#2)",47219962,Babajide,"Brooklyn, Prospect-Lefferts Gardens",Entire home/apt,150.0,123,2019-07-01,2.74,263,3.466881,147.6,0.738191,2018-12-26,40.66086,-73.96159
1481,15027024,Newly renovated 1bd on lively & historic St Marks,8344620,Ethan,"Manhattan, East Village",Entire home/apt,180.0,10,2018-12-31,0.30,0,3.969729,12.0,0.772513,2018-06-27,40.72693,-73.98385
3430,15027024,Newly renovated 1bd on lively & historic St Marks,8344620,Ethan,"Manhattan, East Village",Entire home/apt,180.0,10,2018-12-31,0.30,0,3.869729,12.0,0.772513,2018-06-27,40.72693,-73.98385
3065,16518377,East Village 1BR Apt with all the amenities,3012457,Cody,"Manhattan, East Village",Entire home/apt,200.0,3,2018-07-10,0.16,0,4.676670,3.6,0.694443,2018-01-04,40.72350,-73.97963
5397,16518377,East Village 1BR Apt with all the amenities,3012457,Cody,"Manhattan, East Village",Entire home/apt,200.0,3,2018-07-10,0.16,0,4.676670,3.6,0.694443,2018-01-04,40.72350,-73.97963
3007,17861841,THE CREATIVE COZY ROOM,47591528,Janessa,"Brooklyn, Sheepshead Bay",Private room,99.0,13,2019-05-23,0.52,82,4.806590,15.6,0.937422,2018-11-17,40.59211,-73.94127
368,17861841,THE CREATIVE COZY ROOM,47591528,Janessa,"Brooklyn, Sheepshead Bay",Private room,99.0,13,2019-05-23,0.52,82,4.806590,15.6,0.937422,2018-11-17,40.59211,-73.94127
6438,19477677,Huge sunny room next to subway!,25038748,Justin,"Manhattan, Harlem",Private room,70.0,11,2019-05-11,0.45,0,3.074890,13.2,0.631619,2018-11-05,40.82119,-73.95583
5251,19477677,Huge sunny room next to subway!,25038748,Justin,"Manhattan, Harlem",Private room,70.0,11,2019-05-11,0.45,0,3.074890,13.2,0.631619,2018-11-05,40.82119,-73.95583
5454,21106251,Private Bedroom in Great Brooklyn Apartment,25354313,Tommy,"Brooklyn, Crown Heights",Private room,45.0,9,2019-06-22,0.43,0,3.779114,10.8,0.738191,2018-12-17,40.67359,-73.95812
6832,21106251,Private Bedroom in Great Brooklyn Apartment,25354313,Tommy,"Brooklyn, Crown Heights",Private room,45.0,9,2019-06-22,0.43,0,3.779114,10.8,0.738191,2018-12-17,40.67359,-73.95812
5246,22014840,Sunny Bedroom Only 1 Metro Stop to Manhattan,32093643,Scarlett,"Manhattan, Roosevelt Island",Private room,70.0,2,2018-01-07,0.11,0,4.024336,2.4,0.719426,2017-07-04,40.76211,-73.94887
6068,22014840,Sunny Bedroom Only 1 Metro Stop to Manhattan,32093643,Scarlett,"Manhattan, Roosevelt Island",Private room,70.0,2,2018-01-07,0.11,0,4.024336,2.4,0.719426,2017-07-04,40.76211,-73.94887
5861,23990868,1 Bedroom in Luxury Building,4447548,Grace,"Brooklyn, Bedford-Stuyvesant",Entire home/apt,88.0,8,2019-06-16,0.56,18,4.164548,9.6,0.640106,2018-12-11,40.69336,-73.94453
6132,23990868,1 Bedroom in Luxury Building,4447548,Grace,"Brooklyn, Bedford-Stuyvesant",Entire home/apt,88.0,8,2019-06-16,0.56,18,4.164548,9.6,0.640106,2018-12-11,40.69336,-73.94453
7769,26554879,East Village/Union Square Flat,17400431,Bob,"Manhattan, East Village",Entire home/apt,179.0,32,2019-06-26,2.92,12,3.125513,38.4,0.631764,2018-12-21,40.73177,-73.98691
7116,26554879,East Village/Union Square Flat,17400431,Bob,"Manhattan, East Village",Entire home/apt,179.0,32,2019-06-26,2.92,12,3.125513,38.4,0.631764,2018-12-21,40.73177,-73.98691
5236,29844951,Cozy Home In Queens,49946447,Rah,"Queens, Jamaica",Private room,50.0,1,2019-03-19,0.27,311,4.792923,1.2,0.701232,2018-09-13,40.68842,-73.77677
9425,29844951,Cozy Home In Queens,49946447,Rah,"Queens, Jamaica",Private room,50.0,1,2019-03-19,0.27,311,4.792923,1.2,0.701232,2018-09-13,40.68842,-73.77677
7316,31470004,Private bedroom/Bathroom in a 2 bedroom apartment,71241932,Max,"Manhattan, East Village",Private room,2500.0,0,NaN,NaN,90,NaN,NaN,NaN,2018-04-09,40.72544,-73.97818
9322,31470004,Private bedroom/Bathroom in a 2 bedroom apartment,71241932,Max,"Manhattan, East Village",Private room,2500.0,0,NaN,NaN,90,NaN,NaN,NaN,2018-03-12,40.72544,-73.97818
1338,32610834,Manhattan by the water!,12132369,Omar,"Manhattan, Kips Bay",Entire home/apt,150.0,0,NaN,NaN,9,NaN,NaN,NaN,2018-06-28,40.73767,-73.97384
6313,32610834,Manhattan by the water!,12132369,Omar,"Manhattan, Kips Bay",Entire home/apt,150.0,0,NaN,NaN,9,NaN,NaN,NaN,2018-06-28,40.73767,-73.97384
6085,33346762,2BR Apartment in Brownstone Brooklyn!,50321289,Avery,"Brooklyn, Bedford-Stuyvesant",Entire home/apt,140.0,4,2019-06-14,1.58,4,4.013393,4.8,0.719591,2018-12-09,40.68200,-73.95681
2118,33346762,2BR Apartment in Brownstone Brooklyn!,50321289,Avery,"Brooklyn, Bedford-Stuyvesant",Entire home/apt,140.0,4,2019-06-14,1.58,4,4.013393,4.8,0.719591,2018-12-09,40.68200,-73.95681
5025,33831116,Sonder | Stock Exchange | Collected 1BR + Laundry,219517861,Sonder (NYC),"Manhattan, Financial District",Entire home/apt,229.0,5,2019-06-15,1.92,350,4.026379,6.0,0.601737,2018-12-10,40.70621,-74.01199
5077,33831116,Sonder | Stock Exchange | Collected 1BR + Laundry,219517861,Sonder (NYC),"Manhattan, Financial District",Entire home/apt,229.0,5,2019-06-15,1.92,350,4.026379,6.0,0.601737,2018-12-10,40.70621,-74.01199
1658,35646737,"Private Cabins @ Chelsea, Manhattan",117365574,Maria,"Manhattan, Chelsea",Private room,85.0,1,2019-06-22,1.00,261,4.951714,1.2,0.671388,2018-12-17,40.74946,-73.99627
3340,35646737,"Private Cabins @ Chelsea, Manhattan",117365574,Maria,"Manhattan, Chelsea",Private room,85.0,1,2019-06-22,1.00,261,4.951714,1.2,0.671388,2018-12-17,40.74946,-73.99627
7155,35801208,Comfy 2 bedroom Close To Manhattan,256911412,Taylor,"Brooklyn, Williamsburg",Entire home/apt,101.0,0,NaN,NaN,27,NaN,NaN,NaN,2018-10-17,40.70469,-73.93690
9265,35801208,Comfy 2 bedroom Close To Manhattan,256911412,Taylor,"Brooklyn, Williamsburg",Entire home/apt,101.0,0,NaN,NaN,27,NaN,NaN,NaN,2018-05-03,40.70469,-73.93690

In [26]:
b = airbnb[airbnb["listing_id"].duplicated()] #
display(b.index)

Index([2255, 3007, 3340, 3430, 4187, 5077, 5397, 6068, 6085, 6132, 6313, 6438,
       6562, 6832, 7769, 7933, 8699, 9265, 9322, 9425],
      dtype='int64')

In [29]:
b=airbnb["listing_id"].duplicated(keep='first') #duplicate values
airbnb[b].sort_values("listing_id") #keep = False means shows all duplicated values
print(airbnb[b].sort_values("listing_id").shape)

(20, 17)

In [30]:
airbnb = airbnb.drop_duplicates(subset="listing_id", keep="first") # removes the duplicates
display(airbnb)

,listing_id,name,host_id,host_name,neighbourhood_full,room_type,price,number_of_reviews,last_review,reviews_per_month,availability_365,rating,number_of_stays,5_stars,listing_added,lattitude,longitude
0,13740704,"Cozy,budget friendly, cable inc, private entra...",20583125,Michel,"Brooklyn, Flatlands",Private room,45.0,10,2018-12-12,0.70,85,4.100954,12.0,0.609432,2018-06-08,40.63222,-73.93398
1,22005115,Two floor apartment near Central Park,82746113,Cecilia,"Manhattan, Upper West Side",Entire home/apt,135.0,1,2019-06-30,1.00,145,3.367600,1.2,0.746135,2018-12-25,40.78761,-73.96862
2,21667615,Beautiful 1BR in Brooklyn Heights,78251,Leslie,"Brooklyn, Brooklyn Heights",Entire home/apt,150.0,0,NaN,NaN,65,NaN,NaN,NaN,2018-08-15,40.70070,-73.99517
3,6425850,"Spacious, charming studio",32715865,Yelena,"Manhattan, Upper West Side",Entire home/apt,86.0,5,2017-09-23,0.13,0,4.763203,6.0,0.769947,2017-03-20,40.79169,-73.97498
4,22986519,Bedroom on the lively Lower East Side,154262349,Brooke,"Manhattan, Lower East Side",Private room,160.0,23,2019-06-12,2.29,102,3.822591,27.6,0.649383,2020-10-23,40.71884,-73.98354
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10014,22307861,Lovely 1BR Harlem apartment,16004068,Rachel,"Manhattan, Harlem",Entire home/apt,105.0,4,2018-05-28,0.21,0,4.757555,4.8,0.639223,2017-11-22,40.80379,-73.95257
10015,953275,Apartment For Your Holidays in NYC!,4460034,Alain,"Manhattan, East Harlem",Entire home/apt,125.0,50,2018-05-06,0.66,188,4.344704,60.0,0.648778,2017-10-31,40.79531,-73.93330
10016,3452835,"Artsy, Garden Getaway in Central Brooklyn",666862,Amy,"Brooklyn, Clinton Hill",Entire home/apt,100.0,45,2016-11-27,0.98,0,3.966214,54.0,0.631713,2016-05-24,40.68266,-73.96743
10017,23540194,"Immaculate townhouse in Clinton Hill, Brooklyn",67176930,Sophie,"Brooklyn, Clinton Hill",Entire home/apt,450.0,2,2019-05-31,0.17,99,4.078581,2.4,0.703360,2018-11-25,40.68832,-73.96366
10018,32876011,Private room in a perfect location in the city,59583716,Shai,"Manhattan, Upper East Side",Private room,90.0,1,2019-03-12,0.25,8,4.069096,1.2,0.720249,2018-09-06,40.76174,-73.96625

In [58]:
#duplicate values after removing
b = airbnb["listing_id"].duplicated(keep = 'first')
airbnb[b].sort_values("listing_id")
print(airbnb[b].sort_values("listing_id").shape)

(0, 17)

In [37]:
airbnb["room_type"].unique() #unique rooms

array(['Private room', 'Entire home/apt', 'Private', 'Shared room',
       'PRIVATE ROOM', 'home', '   Shared room      '], dtype=object)

In [53]:
#Cleaning data for room_type... replacing the repeated values
airbnb["room_type"]=airbnb["room_type"].str.replace("Entire home/apt","home")
airbnb["room_type"]=airbnb["room_type"].str.replace("private room","private")
airbnb["room_type"]=airbnb["room_type"].str.lower() #lowercase
airbnb["room_type"]=airbnb["room_type"].str.strip() #removes spaces

<ipython-input-53-45a3df37d764>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  airbnb["room_type"]=airbnb["room_type"].str.replace("Entire home/apt","home")
<ipython-input-53-45a3df37d764>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  airbnb["room_type"]=airbnb["room_type"].str.replace("private room","private")
<ipython-input-53-45a3df37d764>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  airbnb["room_type"]=airbnb["room_type"].str.lower() #lowercase
<ipython-input-53-45a3df37d764>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  airbnb["room_type"]=airbnb["room_type"].str.strip() #removes spaces

In [54]:
airbnb["room_type"].unique()

array(['private', 'home', 'shared room'], dtype=object)

In [55]:
airbnb.groupby("room_type").agg({"price":["mean","max","min"]})

                  price
                   mean     max   min
room_type
home         209.791289  8000.0   0.0
private       87.504252  2850.0   0.0
shared room   70.410959  1800.0  10.0

In [56]:
# Impute price based on conditions
airbnb.loc[(airbnb['price'].isna()) & (airbnb['room_type'] == 'home'), 'price'] = 208.7 #wherever the price is null and room_type is home, replace it with 208.7
airbnb.loc[(airbnb['price'].isna()) & (airbnb['room_type'] == 'private'), 'price'] = 89.02 #wherever the price is null and room_type is private, replace it with 89.02
airbnb.loc[(airbnb['price'].isna()) & (airbnb['room_type'] == 'shared room'), 'price'] = 72.41 #wherever the price is null and room_type is shared room, replace it with 72.41